name: issue-comment-workflow
on: issue_comment

jobs:
  pr-comment:
    if: ${{ github.event.issue.pull_request != null }}  # 올바르게 수정
    runs-on: ubuntu-latest
    steps:
    - name: pr comment
      run: echo ${{ github.event.issue.pull_request }}  # 'guthub' 오타 수정
  
  issue-comment:
    if: ${{ github.event.issue.pull_request == null }}  # 부정 조건을 올바르게 수정
    runs-on: ubuntu-latest
    steps:
      - name: issue comment
        run: echo ${{ github.event.issue.pull_request }}  # 논리상 issue에 대해 출력
